name: shotwell
version: '0.28.2'
summary: Shotwell photo manager
description: |
  Shotwell is a digital photo organizer designed for the GNOME desktop
  environment. It allows you to import photos from disk or camera, organize
  them in various ways, view them in full-window or fullscreen mode, and
  export them to share with others. It is able to manage a lot of different
  image formats, also including raw CR2 files.
confinement: strict
grade: stable

slots:
  dbus-shotwell:
    interface: dbus
    bus: session
    name: org.yorba.shotwell

apps:
  shotwell:
    command: desktop-launch shotwell --datadir $SNAP_USER_COMMON
    desktop: usr/share/applications/shotwell.desktop
    plugs:
      - x11
      - unity7
      - wayland
      - home
      - network
      - mount-observe
      - gsettings
      - removable-media

parts:
  shotwell:
    source: git://git.gnome.org/shotwell.git
    source-tag: shotwell-0.28.2
    plugin: meson
    build-packages:
      - desktop-file-utils
      - gnome-doc-utils
      - libgcr-3-dev
      - libgdata-dev
      - libexif-dev
      - libgee-0.8-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgphoto2-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - libraw-dev
      - librest-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml2
      - valac
      - libaccounts-glib-dev
      - libsignon-glib-dev
      - libunity-dev
      - python-scour
      - intltool
      - appstream-util
      - yelp-tools
      - meson
      - ninja-build
    stage-packages:
      - libc6
      - libcairo2
      - libexif12
      - libgcr-ui-3-1
      - libgdata22
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libglib2.0-0
      - libgphoto2-6
      - libgphoto2-port12
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libjson-glib-1.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libraw16
      - librest-0.7-0
      - libsoup2.4-1
      - libsqlite3-0
      - libunity9
      - libwebkit2gtk-4.0-37
      - libxml2
      - librsvg2-common
      - dbus-x11
      - dconf-tools
      - libgexiv2-2
      - libexiv2-14
    override-build: |
      sed -i 's|Icon=shotwell|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/shotwell.png|g' misc/shotwell.desktop.in
    after: [desktop-gtk3]
